### ISSUE TITLE
Blobfuse path not mounted in container

### ISSUE THREAD

**Issue by jcramer** [Azure/batch-shipyard#162]
Having trouble accessing the blobfuse folder in a task container.  When I print the list of directories using `os.listdirs($AZ_BATCH_TASK_WORKING_DIR)` using python in a running task I don't see "azblob" as a mounted folder in $AZ_BATCH_TASK_WORKING_DIR, I only see the `.shipyard.envlist` directory.  

Given the `config.yaml` file shouldn't I be able to see a "azblob" folder?  Blobfuse is working locally for me as expected.  

```
batch_shipyard:
  storage_account_settings: mystorageaccount
global_resources:
  docker_images:
  - registry.gitlab.com/xxxxx/xxxxxx
  volumes:
    shared_data_volumes:
      azureblobvol:
        volume_driver: azureblob
        storage_account_settings: mystorageaccount
        azure_blob_container_name: userdata
        container_path: $AZ_BATCH_NODE_SHARED_DIR/azblob
        mount_options:
        - --use-https=true
```
**EDIT**:  I did find the fuse drive mounted here in the pool machine: `/mnt/batch/tasks/mounts/`.  Is there an envar for this?

**EDIT 2**: When I look at the directories in AZ_BATCH_NODE_SHARED_DIR all I can see is `.node_prep_finished`

**Comment by alfpark** [comment]
Are you checking for this while SSH'd in?

`container_path: $AZ_BATCH_NODE_SHARED_DIR/azblob` is only visible in the container during task execution, otherwise its on the host in a OS dependent directory (it's not the same across all distros).

**Comment by jcramer** [comment]
@alfpark no I'm printing it to a log from the running job task.

**Comment by alfpark** [comment]
Are you specifying the `azureblobvol` in the `shared_data_volumes` array in your task specification? Take a look at the jobs config doc for more info (search for `shared_data_volumes`).

**Comment by jcramer** [comment]
Yes, as I show in my post above config.yaml file is:

```
batch_shipyard:
  storage_account_settings: mystorageaccount
global_resources:
  docker_images:
  - registry.gitlab.com/xxxxx/xxxxxx
  volumes:
    shared_data_volumes:
      azureblobvol:
        volume_driver: azureblob
        storage_account_settings: mystorageaccount
        azure_blob_container_name: userdata
        container_path: $AZ_BATCH_NODE_SHARED_DIR/azblob
        mount_options:
        - --use-https=true
```
