### ISSUE TITLE
Job with output_data

### ISSUE THREAD

**Issue by WTSParadigm** [Azure/batch-shipyard#165]
I was trying to assign output_data to my trivial POC app, but once I add the output_data node I start getting an error when trying to add the job. My jobs.yaml:
```
job_specifications:
- id: myjob
  tasks:
  - docker_image: wtsparadigm/safeguard:test
    task_factory:
      file:
        azure_storage:
          storage_account_settings: mystorageaccount
          remote_path: mycontainer
        task_filepath: file_name
    output_data:
      azure_storage:
      - storage_account_settings: mystorageaccount
        remote_path: mycontaineroutput
        local_path: output
    command: cmd /c c:/bin/MyTaskApplication.exe {file_name}
```

error:
Traceback (most recent call last):
  File "shipyard.py", line 1796, in <module>
  File "site-packages\click\core.py", line 722, in __call__
  File "site-packages\click\core.py", line 697, in main
  File "site-packages\click\core.py", line 1066, in invoke
  File "site-packages\click\core.py", line 1066, in invoke
  File "site-packages\click\core.py", line 895, in invoke
  File "site-packages\click\core.py", line 535, in invoke
  File "site-packages\click\decorators.py", line 64, in new_func
  File "site-packages\click\core.py", line 535, in invoke
  File "shipyard.py", line 1423, in jobs_add
  File "convoy\fleet.py", line 3032, in action_jobs_add
  File "convoy\batch.py", line 4026, in add_jobs
  File "convoy\batch.py", line 3173, in _add_task_collection
  File "site-packages\azure\batch\operations\task_operations.py", line 338, in add_collection
  File "site-packages\msrest\serialization.py", line 469, in body
  File "site-packages\msrest\exceptions.py", line 45, in raise_with_traceback
  File "site-packages\msrest\serialization.py", line 466, in body
  File "site-packages\msrest\serialization.py", line 990, in __call__
  File "site-packages\msrest\serialization.py", line 1000, in __call__
  File "site-packages\msrest\serialization.py", line 1174, in deserialize_data
  File "site-packages\msrest\serialization.py", line 1201, in deserialize_iter
  File "site-packages\msrest\serialization.py", line 1201, in <listcomp>
  File "site-packages\msrest\serialization.py", line 1185, in deserialize_data
  File "site-packages\msrest\serialization.py", line 990, in __call__
  File "site-packages\msrest\serialization.py", line 1000, in __call__
  File "site-packages\msrest\serialization.py", line 1174, in deserialize_data
  File "site-packages\msrest\serialization.py", line 1201, in deserialize_iter
  File "site-packages\msrest\serialization.py", line 1201, in <listcomp>
  File "site-packages\msrest\serialization.py", line 1185, in deserialize_data
  File "site-packages\msrest\serialization.py", line 1025, in __call__
  File "site-packages\msrest\exceptions.py", line 45, in raise_with_traceback
  File "site-packages\msrest\serialization.py", line 1015, in __call__
  File "site-packages\msrest\serialization.py", line 903, in rest_key_case_insensitive_extractor
  File "site-packages\msrest\serialization.py", line 926, in attribute_key_case_insensitive_extractor
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', Deserializatio
nError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
[3024] Failed to execute script shipyard
