### ISSUE TITLE
Docker files can't be opened: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by hildeweerts** [Azure/batch-shipyard#180]
When I try to use batch-shipyard to run several configurations of the container `hilde/experiment_1`, all tasks fail with the following error:
```
cat: .shipyard.envlist: No such file or directory
python: can't open file 'hyperimp/experiment/experiment.py': [Errno 2] No such file or directory
```
The entry point of my Dockerfile is the following:
```
ENTRYPOINT ["python", "-u", "hyperimp/experiment/experiment.py"]
```
So it looks like the contents of the docker container are not available for the nodes, even though I have added the docker image to the `config.yaml` file as a global resource:
```
batch_shipyard:
  storage_account_settings: mystorageaccount
global_resources:
  docker_images:
    - hilde/experiment_1
```
Does anybody know what I am doing wrong?

Thanks!

**Comment by alfpark** [comment]
Can you paste your `jobs.yaml` (redact anything sensitive)?

**Comment by hildeweerts** [comment]
```
# specify the jobs to execute

# containers are removed upon exit
# pool is removed upon all jobs are completed
job_specifications:
- id: svm
  auto_complete: true # delete pool once all tasks are complete
  tasks:
  - docker_image: hilde/experiment_1
    task_factory: # give task list
      parametric_sweep:
        permutations:
          iterable:
          - '3560'
          - '3902'
          length: 1
    command: --task_id {0} --num 1000 --classifier svm --log False openml_apikey b9398f7994a9f426ec19a122ef61b098 
    remove_container_after_exit: true
```
