### ISSUE TITLE
Task factory: product with iterables?

### ISSUE THREAD

**Issue by hildeweerts** [Azure/batch-shipyard#187]
Is it possible to do a product parameter sweep using iterables instead of a start-stop-step construction using task factory? E.g. if you have 

* list 1: 'a', 'b', 'c'
* list 2: '1', '3'

I'd like to get the combinations: a1, b1, c1, a3, b3, c3. Can this be achieved using existing task factory operations or do I need to create a custom function?

**Comment by alfpark** [comment]
Unfortunately the use of characters in list 1 prevents hte use of `product`.

If you can modify your lists, you can do this with `zip` task factory:
```yaml
task_factory:
  parametric_sweep:
    zip:
    - abcabc
    - '111333'
```

Otherwise you'll need to use a custom generator.
