### ISSUE TITLE
Private Container Registry job doesn't work

### ISSUE THREAD

**Issue by lgilz** [Azure/batch-shipyard#189]
The following job just uses busybox to create a text file in a blob storage. 
Though, the job only works when I use docker_image: busybox in jobs.yaml/tasks/docker_image but not the same image from our privateregistry privatehub.azurecr.io/samples/busybox

I would expect at least an error message that s.th. went wrong. Instead, the job with the private container registry just does not produce the desired output file. 

config.yaml
```
batch_shipyard:
  storage_account_settings: mystorageaccount
global_resources:
  additional_registries:
    docker:
    - privatehub.azurecr.io
  docker_images:
  - busybox
  - privatehub.azurecr.io/samples/busybox
```

jobs.yaml
```
job_specifications:
- id: testjob
  tasks:
  - docker_image: privatehub.azurecr.io/samples/busybox
    command: echo "xyz" > $AZ_BATCH_NODE_SHARED_DIR/busybox.txt
    output_data:
      azure_storage:
      - storage_account_settings: mystorageaccount
        remote_path: tmp1
        local_path: $AZ_BATCH_NODE_SHARED_DIR
        is_file_share: false
```

The documentation actually says for treating private registries:
`(optional) myserver-myorg.azurecr.io is an example property that defines a private container registry to connect to. This is an example to connect to the Azure Container Registry service. The private registry defined here should be defined as the server property in the docker_registry:private property in the global configuration.`

I don't really understand the last sentence - as the global configuration does not have a server or private property.

**Comment by alfpark** [comment]
This is a docbug. Remove the `additional_registries` portion of your configuration. You should have:

config.yaml:
```yaml
batch_shipyard:
  storage_account_settings: mystorageaccount
global_resources:
  docker_images:
  - busybox
  - privatehub.azurecr.io/samples/busybox
```

credentials.yaml:
```yaml
credentials:
  docker_registry:
    privatehub.azurecr.io:
      username: acr_username
      password: acr_user_password
```
