### ISSUE TITLE
Pool resize during runtime

### ISSUE THREAD

**Issue by hildeweerts** [Azure/batch-shipyard#191]
Is it possible to resize the number of nodes in a pool to a number higher than specified in vm_count? I tried to resize my pool in batch labs, but I get a resize timeout error ("Desired number of dedicated nodes could not be allocated as the resize timeout was reached"). My initial pool configuration is as follows:

```
pool_specification:
  id: experiment2
  vm_configuration:
    platform_image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 16.04-LTS
  vm_size: standard_ds5_v2
  vm_count:
    dedicated: 60 # number of nodes
    low_priority: 0 
  max_tasks_per_node: 1
```

My core quota got increased which is why I would like to add more nodes. However, I do not want to remove the current pool and replace it because there are still many jobs running/queued.
