### ISSUE TITLE
Edit entrypoint in YAML job configuration

### ISSUE THREAD

**Issue by f-roche** [Azure/batch-shipyard#232]
#### Problem Description
I am using a Docker container which has the following default entrypoint in its Dockerfile:
```
ENTRYPOINT /bin/bash -c "source setup.sh && dosomestuff_1 $INPUT $OUTPUT && dosomestuff_2 $OUTPUT"
```
This way my Docker container looks like an executable and just have to edit some environment variables ( $INPUT and $OUTPUT) on the fly to specify the job behavior, like this:
```
tasks:
- id: BigJob
  docker_image: private.azurecr.io/mycontainer:latest
  environment_variables:
      INPUT: file.txt
      OUTPUT: file2.txt
```

So now I need to edit this default `entrypoint` since I only want to run `dosomestuff_1` executable without modifying my Docker image. So my undestanding of the `yaml` job configuration file is that I just need to edit the `entrypoint` key like this:
```
tasks:
- id: SmallJob
  docker_image: private.azurecr.io/mycontainer:latest
  environment_variables:
      INPUT: file.txt
      OUTPUT: file2.txt
    entrypoint: /bin/bash -c "source setup.sh && dosomestuff_1 $INPUT $OUTPUT"
```
But this configuration always leads to a task failure (`invalid argument` error).
Is there some specific quotes or escapes that I miss?

#### Batch Shipyard Version
batch-shipyard-3.5.0-cli-win-amd64.exe

#### Expected Results
I expect to run only `dosomestuff_1` executable in my docker container.

#### Actual Results
I am getting `invalid argument` in task `stderr.txt` file.

**Comment by f-roche** [comment]
Well after deep investigations on Docker entrypoint and command it looks like the correct way to configure my container is with the following configuration:
```
tasks:
- id: SmallJob
  docker_image: private.azurecr.io/mycontainer:latest
  environment_variables:
      INPUT: file.txt
      OUTPUT: file2.txt
    entrypoint: /bin/bash
    command: -c "source setup.sh && dosomestuff_1 $INPUT $OUTPUT"
```

with this configuration my task is executed successfully.
