### ISSUE TITLE
SSH user for empty pools

### ISSUE THREAD

**Issue by f-roche** [Azure/batch-shipyard#233]
Hi all,

For now here is my pool configuration file:
```
pool_specification:
  id: MyPool
  vm_configuration:
    platform_image:
      publisher: Canonical
      offer: UbuntuServer
      sku: 16.04-LTS
  vm_size: Standard_D2_v3
  vm_count:
    dedicated: 0
    low_priority: 0
  ssh:
    username: shipyard
    expiry_days: 30
    ssh_public_key_data: ssh-rsa ...
    ssh_private_key: ~/.ssh/id_rsa_shipyard
    allow_docker_access: true
```
Note that I always create empty or auto-scalable pools for data processing based on the quantity of jobs to process.
But with these empty pools I get the following warning message during creation:
`WARNING - cannot add SSH user with zero target nodes`
So at the end the SSH user is not created when pool gets scaled up.

Would it be possible to have it created when node gets created ?

Thanks
