### ISSUE TITLE
Environment variable values with spaces in non-native mode cause execution failures

### ISSUE THREAD

**Issue by alfpark** [Azure/batch-shipyard#234]
Spaces in environment variables are not handled properly in non-native mode.

```yaml
  # jobs config
  environment_variables:
    myenv: hello world
```

This is a regression introduced in this [commit](https://github.com/Azure/batch-shipyard/commit/0891138cd326f8ba557e090e456d9fee4558e58e).
