### ISSUE TITLE
Data Ingress input_data

### ISSUE THREAD

**Issue by JadenLy** [Azure/batch-shipyard#238]
Hello, I am using Shipyard for multiple tasks and now I have an issue here. 

I am running an evaluation of a model which consists of evaluating on multiple datasets. So each datasets corresponds to each task. After all evaluations are done, I have a `merge_task` to combine all the evaluation results together. For this `merge_task`, it requires multiple output files from evaluation output above. 

My current solution is to upload my output to Azure blob and use those required in the form of `input_data` for `merge_task`. However, I found that I have to input lots of formatted data into the node. For example, I have files in the path with `test_1_data/1/results`, `test_2_data/2/results`, etc. I also want them to be under one folder, such as `/data/test_1_data/1/results`, `/data/test_1_data/1/results`, etc/ So I need to move multiple files to the node for `merge_task`. 

```
input_data:
      azure_storage:
      - storage_account_settings: mystorageaccount
        remote_path: projects/
        local_path: /datadrive/results/test_*_data/**/results/
        is_file_share: false
        include: 
          - 'test_*data/**/results/*'
```

I wonder if this works or is there any better option to do it. Thanks!
