### ISSUE TITLE
Pool can auto-scale beyond low priority maximum_vm_count 

### ISSUE THREAD

**Issue by dbradnum** [Azure/batch-shipyard#239]
I've configured a pool to auto-scale up and down based on the `active_tasks` scenario, specifying `bias_node_type: low_priority`. However, when I set the low priority `maximum_vm_count` to be less than the limit imposed by my account quota, and submit more tasks than the pool can handle concurrently, the pool auto-scales up to a number of low priority nodes larger than that maximum_vm_count.

The relevant section of my pool.yaml is as follows:

``` 
  vm_count:
    dedicated: 0
    low_priority: 0
  max_tasks_per_node: 4
  autoscale:
    evaluation_interval: 00:05:00
    scenario:
      name: active_tasks
      maximum_vm_count:
        dedicated: 0
        low_priority: 27
      sample_lookback_interval: 00:05:00
      bias_last_sample: true
      bias_node_type: low_priority
```
So for instance, this should support up to 108 concurrent tasks on low priority nodes only. However, I recently submitted a job with 600+ tasks, and the pool has auto-scaled up to 32 low priority nodes (where it's limited by my quota, though it is trying to scale up further).

When I evaluate the auto-scale formula in the Azure Portal, I see the following output:
```
Evaluation output
$TargetDedicatedNodes
  0
$TargetLowPriorityNodes
  58
$NodeDeallocationOption
  taskcompletion
ActiveTaskAvg
  233
dedicatedVMs
  0
lastsample
  233
lowPriVMs
  58.25
maxIncDedicated
  1.67772e+07
maxIncLowPriority
  1.67772e+07
maxTargetDedicated
  0
maxTargetLowPriority
  27
maxTasksPerNode
  4
minTargetDedicated
  0
minTargetLowPriority
  0
preemptcount
  0
rebalance
  0
redistVMs
  0
remainingVMs
  0
reqVMs
  58.25
samplepercent
  100
samplevecavg
  165.8
sli
  5m
```

From a quick look at the underlying code, I _think_ the root cause is this block:
https://github.com/Azure/batch-shipyard/blob/cc33117f82bc44adfcea13111e1ba678b7cfea46/convoy/autoscale.py#L176-L182 

It appears that line 176 correctly refers to maxTargetLowPriority, but then lines 179-180 overwrite the value assigned to lowPriVMs, and don't deal with the case where reqVMs > maxTargetLowPriority ?
