### ISSUE TITLE
Scheduling order of the tasks

### ISSUE THREAD

**Issue by stity** [Azure/batch-shipyard#240]
#### Problem Description
When I create multiple jobs with multiple tasks in each job on a pool with a single node, the order of execution of the tasks is not convenient.
#### Batch Shipyard Version
3.5.0-cli-win-amd64
#### Steps to Reproduce
Create two jobs with three tasks in each job on a pool with a single node.
Task 2 depends on Task 1 and Task 3 depends on Task 1 and Task 2.
#### Expected Results
I expect the order of execution to be the following : 
- Job 1 Task 1
- Job 1 Task 2
- Job 1 Task 3
- Job 2 Task 1
- Job 2 Task 2
- ..

In other words, I expect the first job to finish before any task of the second job starts.
#### Actual Results
I observe the following order of execution : 
- Job 1 Task 1
- Job 2 Task 1
- Job 1 Task 2
- Job 2 Task 2
- ...
#### Redacted Configuration
Each job has the same configuration except for the input data.

```
job_specifications:
- id:  job_1
  allow_run_on_missing_image: true
  auto_complete: true 
  priority: 0 
  remove_container_after_exit : true

  tasks:
  - id: ConvertDicom2Nifti
    docker_image: container_name1
    environment_variables:
      ...
    entrypoint: /bin/bash
    command: -c "..."
    input_data:
      azure_storage:
      - storage_account_settings: ...
        remote_path: ...
        include:
        - '*.dcm'


  - id: SkullStrip
    docker_image: container_name2
    environment_variables:
      ...
    entrypoint: /bin/bash
    command:  -c "..."
    depends_on:
    - ConvertDicom2Nifti

  - id: MaskType
    docker_image: container_name1
    environment_variables:
      ...
    entrypoint: /bin/bash
    command: -c "..."
    depends_on :
      - ConvertDicom2Nifti
      - SkullStrip

```

#### Additonal Comments
There is two problems with this order of scheduling : 
- I cannot scale the pool once Job 1 Task 1 and Job 2 Task 1 are executed because each needs to run on a single node.
- I get to see the results only once every job is finished instead of seeing the results progressively.

I may have missed an option in the configuration to enforce this order of execution.

**Comment by stity** [comment]
Your solution would work if the pool was not scaled up.
But I want to be able to scale up the pool once the first job has already started.
Ideally the first job would then run entirely on the first node and the second job would run entirely on the second node.
Right now the following scenario is possible : 
- Pool is scaled to one node
- 2 jobs are submitted
- J1T1 starts on node 1
- J1T1 finished
- J2T1 starts on node 1
- Pool scaled to two nodes
- J1T2 starts on node 2
- ...

I want to prevent this and rather enforce this scenario : 
- Pool is scaled to one node
- 2 jobs are submitted
- J1T1 starts on node 1
- J1T1 finished
- J1T2 starts on node 1
- Pool scaled to two nodes
- J2T1 starts on node 2
- ...

I want each job to be executed as a block by a single node.

**Comment by alfpark** [comment]
There's no way to currently do this automatically without job dependency support at the Azure Batch level. You can manually accomplish this by polling for task completion and then manually resizing the pool; you should be able to accomplish both of these actions via the CLI.

**Comment by stity** [comment]
Do you know if job dependency are planned to be supported by Azure Batch ?
Anyway, thank you for your time and your reactivity. 👍

**Comment by alfpark** [comment]
It's in our backlog, but can't give a firm ETA at this time. You can open up a feature request [here](https://github.com/Azure/Batch/issues) for tracking.

**Comment by f-roche** [comment]
@alfpark, regarding task scheduling, does task dependency force the execution of all tasks of a job on the same node?

Let's assume we are using the following job definition:
```
job_specifications:
- id: Job1
  tasks:
  - id: Task1
    docker_image: generate_new_files_locally
  - id: Task2
    docker_image: upload_new_files
    depends_on:
    - Task1
```
in this example `Task2` will upload files that have been previously generated by `Task1` on the node (e.g. $AZ_BATCH_NODE_SHARED_DIR).
Does this dependency impose the tasks to be executed on the same node?
