### ISSUE TITLE
Merge task never gets activated

### ISSUE THREAD

**Issue by veonua** [Azure/batch-shipyard#256]
#### Problem Description
I have same 400 ocr jobs and merge task, now its 15 hours pool is idle, but merge task newer started

#### Batch Shipyard Version
3.6.1

#### Steps to Reproduce
run ocr with failing jobs

#### Expected Results
merge task runs after tasks done

#### Actual Results
keeps "active" for hours

#### Redacted Configuration
```
job_specifications:
- id: ocr
  
  tasks:  
  - docker_image: tesseractshadow/tesseract4re
    
    task_factory:
        file:
          azure_storage:
            storage_account_settings: mystorageaccount
            remote_path: test
            is_file_share: true
            include:
            - '*_1.jpe'
            
          task_filepath: file_name

    command: /bin/bash -c "install -Dv /dev/null {file_path} | tesseract $AZ_BATCH_TASK_WORKING_DIR/{file_name} {file_path}"
    output_data:
      azure_storage:
      - storage_account_settings: mystorageaccount
        remote_path: test
        local_path: $AZ_BATCH_TASK_WORKING_DIR/
        is_file_share: true
        include:
        - "*.txt"

  merge_task:
    docker_image: python:3.7-alpine3.7
    input_data:
      azure_storage:
      - storage_account_settings: mystorageaccount
        remote_path: test
        is_file_share: true
        blobxfer_extra_options: '--strip-components 2'
    command: /bin/sh -c "cat ./*/*/*/*.txt > results.txt"
    output_data:
      azure_storage:
      - storage_account_settings: mystorageaccount
        remote_path: output/results
        is_file_share: true
        local_path: $AZ_BATCH_TASK_WORKING_DIR/results.txt

```
