### ISSUE TITLE
Multiple jobs output_data configurations doesn't work independently

### ISSUE THREAD

**Issue by maroony** [Azure/batch-shipyard#310]
#### Problem Description

If you use multiple `output_data` configurations in your `jobs.yaml` file, they do not work independently. If the first will end in an error, the second won't start. This is important, when you configure one for log files. 

#### Batch Shipyard Version

3.8.1

**Comment by alfpark** [comment]
Can you please provide an example configuration that demonstrates this?

**Comment by alfpark** [comment]
This is limited only to non-native pools.

**Comment by maroony** [comment]
This is a snippet from my `jobs.yaml` file:

````yaml
   output_data:
      azure_storage:
        # data
      - storage_account_settings: my_storage_account
        local_path: ${AZ_BATCH_TASK_DIR}/data
        remote_path: /my/remote/path/to/data
        is_file_share: false
        condition: taskcompletion  
        # logs
      - storage_account_settings: my_storage_account
        local_path:  ${AZ_BATCH_TASK_DIR}/logs"
        remote_path: /my/remote/path/to/logs
        is_file_share: false
        condition: taskcompletion
````

Here you can see 2 `output_data` configurations. If there is an error within the data transfer, the transfer for the logs won't start. So my workaround for the moment is to switch these configurations, to always get my logs.
