### ISSUE TITLE
Support for multiple task factories

### ISSUE THREAD

**Issue by sebastiankochman** [Azure/batch-shipyard#321]
#### Feature Request Description
Need for a parameter sweep involving multiple smaller product_iterables (e.g.: try combinations [x,y] * [a,b] and [z,w] * [c,d], but don't waste time on [x,y] * [c,d], because either the user already knows it's not promising or maybe even those combinations don't make any sense)

#### Describe Preferred Solution
Add "id" or "task_prefix" (defaults to "task") field under "task_factory" and allow multiple factories. Jobs yaml could look like:

```
 - task_factory
   task_prefix: deep_training
   parametric_sweep:
      [...]

 - task_factory
   task_prefix: shallow_training
   parametric_sweep:
      [...]
```

These could produce tasks: deep_training_0000, deep_training_0001, [...], shallow_training_0000, shallow_training_0001 [...].

#### Describe Alternatives Considered
If there are some existing alternatives for this scenario built into Shipyard, please let me know.
