### ISSUE TITLE
Task factory on related input files

### ISSUE THREAD

**Issue by davidealbanese** [Azure/batch-shipyard#326]
Bioinformatic tasks may require related pairs (or triplets, etc) of files as input. A typical example is the alignment of paired DNA reads to a reference genome. In this example read pairs are saved in 2 separated files, where the prefix indicates the sample ID (e.g. in the following example `SAMPLE1` or `test/TEST0`) and the suffix specifies the read ID (e.g. `_R1.fastq` and `_R2.fastq`).

Now, let's assume that `mycontainer` contains the following blobs:

- `SAMPLE1_R1.fastq`
- `SAMPLE1_R2.fastq`
- `test/TEST0_R1.fastq`
- `test/TEST0_R2.fastq`

Then we would generate 2 tasks, one task for every sample found in the container
(i.e. `SAMPLE1` and `test/TEST0`):

```
Task 0:
    /bin/bash -c "echo file_path_0=SAMPLE1_R1.fastq file_path_1=SAMPLE1_R2.fastq"
Task 1:
    /bin/bash -c "echo file_path_0=test/TEST0_R1.fastq file_path_1=test/TEST0_R2.fastq"
```

The task factory could be:

```yaml
task_factory:
  file:
    azure_storage:
      storage_account_settings: mystorageaccount
      remote_path: mycontainer
    task_filepath: file_path
    task_suffix:
      - '_R1.fastq'
      - '_R2.fastq'
command: /bin/bash -c "echo file_path_0={file_path_0} file_path_1={file_path_1}"
```

The other keyword formatters would be `url_0`, `url_1`, `file_path_with_container_0`, etc.

Note that this feature could be useful in other common contexts (e.g. analysis of images at different times, audio samples from different sources, etc.).

Thank you,
Davide
