### ISSUE TITLE
All nodes in pool in state `starttaskfailed`: apt-get update "Hash Sum mismatch"

### ISSUE THREAD

**Issue by elemakil** [Azure/batch-shipyard#330]
#### Problem Description

I have been using Azure Batch Shipyard with VMs of type STANDARD_NC6 succesfully for a while. As of today, creating a new pool results in a defunct pool with all nodes in `starttaskfailed` state.

Using the Azure Batch Explorer I've checked the stderr.txt log in the `startup` folder:

```
WARNING: No swap limit support
WARNING: No swap limit support
nvidia-persistenced failed to initialize. Check syslog for more details.
nvidia-persistenced failed to initialize. Check syslog for more details.
nvidia-persistenced failed to initialize. Check syslog for more details.
nvidia-persistenced failed to initialize. Check syslog for more details.
nvidia-persistenced failed to initialize. Check syslog for more details.
dpkg-query: package 'blobfuse' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
E: Failed to fetch https://packages.microsoft.com/ubuntu/16.04/prod/dists/xenial/main/binary-amd64/Packages.bz2  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
E: Failed to fetch https://packages.microsoft.com/ubuntu/16.04/prod/dists/xenial/main/binary-amd64/Packages.bz2  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

The last section repeats until the pool cancels the starttask. I can provide additional logs if needed.

#### Batch Shipyard Version

3.7.0 & 3.9.0

#### Steps to Reproduce

Create pool and wait.

#### Expected Results

The pool gets created and the job + tasks start properly.

#### Actual Results

All nodes in the pool get stuck in "starttaskfailed"

#### Redacted Configuration
*pool*:
```
pool_specification:
  id: debug-pool
  vm_configuration:
    platform_image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 16.04-LTS
      native: true
  vm_count:
    dedicated: 1
    low_priority: 1
  vm_size: STANDARD_NC6
```
