### ISSUE TITLE
Key "condition" not defined for merge_task/output_data/azure_storage/*

### ISSUE THREAD

**Issue by sebastiankochman** [Azure/batch-shipyard#336]
#### Problem Description
Property "condition" does not seem to be supported for merge_task.

#### Batch Shipyard Version
3.9.1

#### Steps to Reproduce
```
  merge_task:
    output_data:
      azure_storage:
      - storage_account_settings: batch_storage_account
        remote_path: logs
        local_path: $$AZ_BATCH_TASK_DIR
        is_file_share: true
        condition: taskcompletion
        include:
        - stdout.txt
        - stderr.txt
```

#### Actual Results
```
2020-01-16 13:53:33.462 ERROR - Jobs Configuration Schema validation failed:
 - Key 'condition' was not defined. Path: '/job_specifications/0/merge_task/output_data/azure_storage/0'.
```

#### Additonal Comments
Seems to work fine for regular tasks and inside task_factory, but not for merge_task.
