### ISSUE TITLE
autoscale pool is inconsistent with multi-instance tasks

### ISSUE THREAD

**Issue by themorey** [Azure/batch-shipyard#343]
#### Problem Description
Submitting a job with multi-instance task to an autoscale pool doesn't always start

#### Batch Shipyard Version
3.9.0

#### Steps to Reproduce
Submit an autoscale pool:
```
pool_specification:
  id: singularity-mpibench-mvapich
  vm_configuration:
    platform_image:
      offer: CentOS-HPC
      publisher: OpenLogic
      sku: '7.7'     
  vm_count:
    dedicated: 0
    low_priority: 0
  vm_size: STANDARD_HC44rs
  autoscale:
    evaluation_interval: 00:10:00
    scenario:
      name: active_tasks
      maximum_vm_count:
        dedicated: 4
        low_priority: 0
      maximum_vm_increment_per_evaluation:
        dedicated: -1
        low_priority: -1
  inter_node_communication_enabled: true
  ssh:
    username: shipyard
  container_runtimes:
    install:
      - singularity
```
Submit a multi-instance job:
```
job_specifications:
- id: osu-benchmark-mvapich2
  tasks:
  - singularity_image: library://alfpark/mvapich/mvapich:2.3.2
    environment_variables:
      BENCHMARK: collective/osu_allreduce
      BENCHMARK_ARGS: -f
    multi_instance:
      num_instances: 2
      mpi:
        runtime: mvapich
        processes_per_node: 1
      pre_execution_command: module load mpi/mvapich2
    command: /bin/bash -c "cd /usr/local/libexec/osu-micro-benchmarks/mpi; ./${BENCHMARK} ${BENCHMARK_ARGS}"
```
#### Expected Results
If pool is at 0 the job should wait in the queue until the next resize event (every 10 mins).  At that time 2 nodes should scale up and run the configured task.

#### Actual Results
After 30 min the pool does not scale and the task has not run.

#### Redacted Configuration
```
batch_shipyard:
  storage_account_settings: mystorageaccount
global_resources:
  singularity_images:
     signed:
      - image: library://alfpark/mvapich/mvapich:2.3.2
        signing_key:
          fingerprint: B55AC090E5139130C112A5783C4D545F457737EB
```

#### Additonal Comments
This behavior is inconsistent.  After submitting a trial single instance job to a different autoscale pool, I tried the multi-instance job again and it worked.
