### ISSUE TITLE
Start task fails: CXXABI_1.3.11, GLIBCXX_3.4.22 not found (required by blobfuse)

### ISSUE THREAD

**Issue by sebastiankochman** [Azure/batch-shipyard#351]
#### Problem Description
All of our auto-scale jobs started failing yesterday on starttask with the following in stderr:

```
dpkg-query: package 'blobfuse' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
blobfuse: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by blobfuse)
blobfuse: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by blobfuse)
```

#### Batch Shipyard Version
3.9.1

#### Redacted Configuration
pool.yaml:
```
pool_specification:
  id: ubuntu-1604-nc6
  vm_configuration:
    platform_image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 16.04-LTS
  vm_size: nc6
  vm_count:
    dedicated: 0
    low_priority: 0
  max_tasks_per_node: 1
  autoscale:
    evaluation_interval: 00:05:00
    scenario:
      name: active_tasks
      maximum_vm_count:
        dedicated: 4
        low_priority: 16
      maximum_vm_increment_per_evaluation:
        dedicated: -1
        low_priority: -1
      node_deallocation_option: taskcompletion
      bias_node_type: low_priority
  reboot_on_start_task_failed: true
  attempt_recovery_on_unusable: true
  virtual_network:
    arm_subnet_id: ...
```

#### Additonal Comments
Please let me know if you need any more info or if the issue is not Shipyard-specific and we should look for a solution elsewhere.
