### ISSUE TITLE
"Error response from daemon" occurred when pull shipyard image from default registry.

### ISSUE THREAD

**Issue by coolstate** [Azure/batch-shipyard#372]
#### Problem Description
"Error response from daemon" occurred when pull shipyard image from default registry.
node can not be started.

#### Batch Shipyard Version
3.9.1

##### pool.yaml
```
pool_specification:
  id: XXXXXXXXX
  vm_configuration:
    platform_image:
      offer: centos-container
      publisher: microsoft-azure-batch
      sku: 7-8
  vm_count:
    dedicated: 1
    low_priority: 0
  vm_size: Standard_A2_v2
  reboot_on_start_task_failed: true
...
```

#### Additional Logs
```
...
2022-03-30T03:11:06,126827498+0000 - DEBUG - Pulling Docker Image: mcr.microsoft.com/blobxfer:1.9.4 (fallback: 0)
1.9.4: Pulling from blobxfer
89d9c30c1d48: Pulling fs layer
6de18253c5d3: Pulling fs layer
89d9c30c1d48: Verifying Checksum
89d9c30c1d48: Download complete
6de18253c5d3: Verifying Checksum
6de18253c5d3: Download complete
89d9c30c1d48: Pull complete
6de18253c5d3: Pull complete
Digest: sha256:94192812382de05b77d8766720cf4c22cc84fd15c86a838a043366fa2047af83
Status: Downloaded newer image for mcr.microsoft.com/blobxfer:1.9.4
mcr.microsoft.com/blobxfer:1.9.4
2022-03-30T03:11:12,330795698+0000 - DEBUG - Pulling Docker Image: mcr.microsoft.com/azure-batch/shipyard:3.9.1-cargo (fallback: 0)
2022-03-30T03:11:42,631140014+0000 - ERROR - Error response from daemon: Head "https://mcr.microsoft.com/v2/azure-batch/shipyard/manifests/3.9.1-cargo": dial tcp 204.79.197.219:443: i/o timeout
2022-03-30T03:11:42,632379527+0000 - ERROR - No fallback registry specified, terminating
```

#### Additonal Comments
we don't have a fallback registry setting.

I want to make sure:

1.  how can I change the setting to retry pulling image or retry start task?
   I can see "Max task retry count" setting in start task section when create pool with azure portal, so I want to know whether I can set "Max task retry count" in shipyard config file or not.

2.  I can find "reboot_on_start_task_failed" parameter in pool.yaml. Does this parameter can resolve this issue?

3.   Do you have any suggestion about resolving this issue

<img width="960" alt="pool_issue" src="https://user-images.githubusercontent.com/3975243/160836706-8a8aa3da-957a-49db-8488-4066df2ba4d0.PNG">
?
