### ISSUE TITLE
How can I set docker image name as a environment variable?

### ISSUE THREAD

**Issue by coolstate** [Azure/batch-shipyard#373]
### config.yaml
```
batch_shipyard:
  storage_account_settings: myaccount
global_resources:
  additional_registries:
    docker:
    - xxxx.azurecr.io
  docker_images: 
  - xxxx.azurecr.io/xxxxdev:v1.0
 ```

### jobs.yaml
```
job_specifications:
- id: job1
  auto_complete: true
  max_task_retries: 0
  auto_pool:
    keep_alive: false
    pool_lifetime: job
  exit_conditions:
    default:
      exit_options:
        job_action: terminate
  tasks:
  - id: task1
    docker_image: xxxx.azurecr.io/xxxxdev:v1.0
    command: python3 test1.py
  - id: task2
    docker_image: xxxx.azurecr.io/xxxxdev:v1.0
    command: python3 test2.py
    depends_on:
    - task1
 ```

I have a docker image named `xxxx.azurecr.io/xxxxdev:v1.0`.
And I have a lot of tasks in jobs.yaml, each task is related with the docker image.
I don't want to config repeated docker image name for each task.
I'm considering if I can set a environment variable for `xxxx.azurecr.io/xxxxdev:v1.0`, such as {my_docker_image}
so I can  change jobs.yaml as below.
I want to know where can I set a environment variable named {my_docker_image} which value is  `xxxx.azurecr.io/xxxxdev:v1.0`.

```
  tasks:
  - id: task1
    docker_image: {my_docker_image}
    command: python3 test1.py
  - id: task2
    docker_image: {my_docker_image}
    command: python3 test2.py
    depends_on:
    - task1
 ```
